"""Adicionando campo hora_ocorrencia

Revision ID: 413659e35ca1
Revises: 807b0a23bb4d
Create Date: 2025-03-17 00:18:46.703673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413659e35ca1'
down_revision = '807b0a23bb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objeto_roubado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_ocorrencia', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objeto_roubado', schema=None) as batch_op:
        batch_op.drop_column('hora_ocorrencia')

    # ### end Alembic commands ###
